Adds Juice Boxes!
SheepFighter/Stratus pull request #3
Opened 2017-09-16 02:34 UTC by ShibberinoShipperino

New Juice Boxes Available to Drink!

Drinks:

![drinks](https://user-images.githubusercontent.com/26367320/30508476-a383dea0-9a8f-11e7-9bf2-7780a1c35eed.png)

Barry's Red Kola
Mingus Dew
Starman Sparkle
Queen's Haven
Aloha Coe
Blurred Limes
Mango Reinhardt

pls be gentle this is my first time attempting to code thank u i think this is still probably not gonna work or act like a can

Thanks to Danny (Counter) and Flipping Out for assistance.

2017-09-16 10:44 UTC, Birdtalon requested changes

2017-09-16 10:44 UTC, Birdtalon commented on code/modules/reagents/chemistry/reagents/drink_cold.dm
>  /datum/reagent/consumable/drink/cold/rewriter/on_mob_life(mob/living/M)
Move this proc back up so it sits underneath `/datum/reagent/consumable/drink/cold/rewriter` it's not necessary to do so but it's better when someone looks at this file again.

2017-09-16 11:09 UTC, MrFroztee commented
Are these available in a vendor, or are they just implemented into the code for further use?

2017-09-16 12:49 UTC, ShibberinoShipperino commented
They aren't added to vendors yet, I've also updated it with the changes.

2017-09-17 02:51 UTC, msgerbs commented
I would suggest making 3 sprites for each: A normal sprite, a sprite with a straw in it (for when it's opened) and a crushed sprite? I don't think there is currently a different sprite for open/closed but that could be added and it would be nice to have the sprites ready to go.

2017-09-24 22:28 UTC, merged